### ISSUE TITLE
Docker compose for fast start

### ISSUE THREAD

**Issue by Bobreshovr** [TinkoffCreditSystems/ISA#1]
ISA has many systems for works and will be cool to create Docker compose for start.

**Comment by mmikirtumov** [comment]
Please take a look on files 
https://github.com/TinkoffCreditSystems/ISA/blob/master/build/docker-compose.yml
https://github.com/TinkoffCreditSystems/ISA/blob/master/scripts/docker.rebuild-and-run.cmd

Please feel free to reopen the issue if you need other tools and files.
