### ISSUE TITLE
Create new project for Jira knowledge source

### ISSUE THREAD

**Issue by mmikirtumov** [TinkoffCreditSystems/ISA#11]
**Is your feature request related to a problem? Please describe.**
Integrate Jira knowledge source as separate project

**Describe the solution you'd like**
Move code from
https://github.com/TinkoffCreditSystems/ISA/blob/master/src/Tinkoff.ISA.AppLayer/Jobs/JiraJob.cs
to seperate project and allow to add Jira in Scheduler project as
serviceCollection.AddJira()

Register dependencies as https://www.stevejgordon.co.uk/asp-net-core-dependency-injection-registering-multiple-implementations-interface

Issue has been blocked by #10

**Comment by lesley29** [comment]
Do you mind if I do this issue with #10?
