### ISSUE TITLE
Knowledge source should work and save into elastic parallel

### ISSUE THREAD

**Issue by mmikirtumov** [TinkoffCreditSystems/ISA#12]
**Is your feature request related to a problem? Please describe.**
Now we are going to optimize scheduler work to only get data from specific provider #10 . It will be better to create some mechanism to run this knowledge base parallel and do not queue them.

**Describe the solution you'd like**
It will be better to use semaphore to allow specific number of threads work parallel and get data and save them into database. In this ticket it will be better to create also saving mechanism.

**Describe alternatives you've considered**
Maybe we can think about Producer Consumer Pattern (https://www.dotnetcurry.com/patterns-practices/1407/producer-consumer-pattern-dotnet-csharp)

**Additional context**
Do not forget to keep some additional data in mongo which will help the knowledge provider to run the next job.

**Comment by vmayushan** [comment]
I think we can use
`
  Parallel.ForEach(messages ,
     new ParallelOptions{MaxDegreeOfParallelism = 4},
            x => Process(x);
        );
`

in [JobsActivator.cs](https://github.com/TinkoffCreditSystems/ISA/blob/master/src/Tinkoff.ISA.Scheduler/Activators/JobsActivator.cs) instead of ` foreach (var jobType in jobTypes)`.

It will be simpler than SemaphoreSlim, do use see any cons?

**Comment by mmikirtumov** [comment]
@vmayushan 
What you think about something in the following way

Parallel.ForEach(messages , new ParallelOptions{MaxDegreeOfParallelism = 4}, x => Process(x); );

```
Process(x) {
// the logic of multiple try after some milliseconds for as we have for
for(int x=0; x< 4; i++)
{
try {
doSomeJob(x);
}
catch(Exception ex) {
// logic of logging exception and retrying, if not just add exception and send to up like
https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-handle-exceptions-in-parallel-loops
}
}
}

```And I hope we will not block the execution of other providers
